### PR TITLE
Add undo and redo

### PR DESCRIPTION
**Pull request by bigfoodK**
**Notice**
It saves whole state of redux
This can be performance issue

R and Ctrl+Z for undo
Shift+R and Ctrl+Shift+Z for redo

### CODE REVIEW

**Comment by namse** [comment]
@bigfoodK I have a suggestion about implementation of history.

What about keep state using `store.subscribe` and restore with that?
Below is psudocode.

```typescript
const stateStorage: state[] = [];
let stateStorageIndex;
store.subscribe((nextState) => {
  stateStorage.removeElementsAfter(stateStorageIndex);
  stateStorage.push(nextState);
  stateStorageIndex = stateStorage.length - 1;
});

function Undo() {
  const state = stateStorage[stateStorageIndex - 1];
  stateStorageIndex -= 1;
  setState(state);
}

function Redo() {
  const state = stateStorage[stateStorageIndex + 1];
  if (!state) {
    throw new Error('cant redo');
  }
  stateStorageIndex += 1;
  setState(state);
}
```

**Comment by bigfoodK** [comment]
**Consider points**

1. There is some functions that does multiple dispatch
https://github.com/team-luda/Milishita-NoteEditor/blob/7415637ff8c14b361d439b2b28098e624daf93e4/web/src/utils/note.ts#L27-L33
It's because the function dispatch multiple states
So If You keep state on `dispatch `or `action`, You have to becareful not to keep state multiple time

2. There is one function, In here, It has to keep state, but In there, It should not to keep state
https://github.com/team-luda/Milishita-NoteEditor/blob/7415637ff8c14b361d439b2b28098e624daf93e4/web/src/runAddLongNoteProcess.ts#L68-L76
`dispatch(BarAction.addNote());`
In adding single note or making start note of long note, This function has to keep state,
But in adding end note of long note, That should not be.
If the function keep state in adding end note of long note,
Undo  after adding long note, It goes to long note editting process,
There is issue, Even if state goes back, We can't edit again, It's because long note adding process is over already.

**Solutions**

**Consider point 1**
Just add history.push() to first thing of dispatches
dispatch(someAction.some)    <- just add to this
dispatch(somesomeAction.some)
dispatch(somesomesomebarAction.some)

**Consider point 2**
Just add new action that same function as different name

With these solutions, How about just add `editHistory.push()` to actions with `.gen`file
ex) in bar.gen
`addNote() -someWord`

then, in barActions.ts
```
function addNote(...) {
  editHistory.push()
  ...
}
```

like this, Is it look good to you?

**Comment by namse** [comment]
1. multiple actions : Batching
You can create `Batch Reducer` which get types which contains multiple actions.
Check this description -> https://github.com/reduxjs/redux/issues/911#issuecomment-149361073

2. Long Note Procedure Issue
Maybe we have to re-implement long Note adding procedure from async function to redux actions...

**Comment by bigfoodK** [comment]
Fixed issues.

Thank you for your advice.

**Pull request merged**
